
xgboost_params:
  objective: binary:logistic
  eval_metric: auc
  max_depth: 6
  learning_rate: 0.1
  n_estimators: 100
  subsample: 0.8
  colsample_bytree: 0.8
  gamma: 0
  min_child_weight: 1
  scale_pos_weight: 1
  reg_alpha: 0
  reg_lambda: 1
  random_state: 42
  booster: gbtree